### ISSUE TITLE
Error after extracting

### ISSUE THREAD

**Issue by madhurdev** [jesstelford/extract-to-react#58]
**Error**:

```
<TODO: Fill in your error>
```

**Version**: v1.0.2

**URL**: https://flone.reactdemo.hasthemes.com/home-grid-banner

**Extracting**:

```html
<img src="/assets/img/product/hm6-pro-3.jpg" alt="" data-snapshooter-original-id="" id="IMG_1">
```
```css
#IMG_1 {
    block-size: 626.422px;
    box-sizing: border-box;
    cursor: pointer;
    height: 626.422px;
    inline-size: 381px;
    perspective-origin: 190.5px 313.203px;
    text-align: left;
    text-size-adjust: 100%;
    transform: matrix(1, 0, 0, 1, 0, 0);
    transform-origin: 190.5px 313.211px;
    vertical-align: middle;
    width: 381px;
    font: 14px / 24px Poppins, sans-serif;
    transition: all 0.5s ease 0s;
}/*#IMG_1*/

#IMG_1:after {
    box-sizing: border-box;
    cursor: pointer;
    text-align: left;
    text-size-adjust: 100%;
    font: 14px / 24px Poppins, sans-serif;
}/*#IMG_1:after*/

#IMG_1:before {
    box-sizing: border-box;
    cursor: pointer;
    text-align: left;
    text-size-adjust: 100%;
    font: 14px / 24px Poppins, sans-serif;
}/*#IMG_1:before*/


```
